export const CHANGE_COlOR_BLUE= 'CHANGE_COlOR_BLUE';
export const CHANGE_COlOR_YELLOW= 'CHANGE_COlOR_YELLOW';
export const CHANGE_COlOR_GREY= 'CHANGE_COlOR_GREY';
export const CHANGE_COlOR_AFTER_RE= 'CHANGE_COlOR_AFTER_RE';


